Order Rust test job before Rust build job

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -62,6 +62,35 @@ jobs:
           path: ./pkl/.out/uplare@${{ steps.version.outputs.version }}/
           if-no-files-found: error
 
+  rust-test:
+    runs-on: ubuntu-latest
+    name: Test Rust CLI
+    steps:
+      - name: Install Rust
+        uses: dtolnay/rust-toolchain@master
+        with:
+          toolchain: stable
+          components: rustfmt, clippy
+      - uses: actions/checkout@v6
+      - name: Run tests
+        id: cargo-test
+        continue-on-error: true
+        run: cargo test
+      - name: Check formatting
+        id: cargo-fmt
+        continue-on-error: true
+        run: cargo fmt -- --check
+      - name: Check clippy
+        id: cargo-clippy
+        continue-on-error: true
+        run: cargo clippy -- -D warnings
+      - name: Fail if any Rust check failed
+        run: |
+          if [[ "${{ steps.cargo-test.outcome }}" != "success" || "${{ steps.cargo-fmt.outcome }}" != "success" || "${{ steps.cargo-clippy.outcome }}" != "success" ]]; then
+            echo "At least one Rust check failed"
+            exit 1
+          fi
+
   rust-build:
     strategy:
       matrix:
@@ -91,35 +120,6 @@ jobs:
           name: uplare-${{ matrix.target }}
           path: ./target/${{ matrix.target }}/release/uplare
           if-no-files-found: error
-
-  rust-test:
-    runs-on: ubuntu-latest
-    name: Test Rust CLI
-    steps:
-      - name: Install Rust
-        uses: dtolnay/rust-toolchain@master
-        with:
-          toolchain: stable
-          components: rustfmt, clippy
-      - uses: actions/checkout@v6
-      - name: Run tests
-        id: cargo-test
-        continue-on-error: true
-        run: cargo test
-      - name: Check formatting
-        id: cargo-fmt
-        continue-on-error: true
-        run: cargo fmt -- --check
-      - name: Check clippy
-        id: cargo-clippy
-        continue-on-error: true
-        run: cargo clippy -- -D warnings
-      - name: Fail if any Rust check failed
-        run: |
-          if [[ "${{ steps.cargo-test.outcome }}" != "success" || "${{ steps.cargo-fmt.outcome }}" != "success" || "${{ steps.cargo-clippy.outcome }}" != "success" ]]; then
-            echo "At least one Rust check failed"
-            exit 1
-          fi
 
   release:
     needs: [pkl, rust-build, rust-test]
